export const FETCH_BOARDS_REQUEST = 'FETCH_BOARDS_REQUEST'
export const FETCH_BOARDS_SUCCESS = 'FETCH_BOARDS_SUCCESS'
export const FETCH_BOARDS_FAILURE = 'FETCH_BOARDS_FAILURE'

export const ADD_BOARD = 'ADD_BOARD'
export const ADD_COLUMN = 'ADD_COLUMN'
export const ADD_TASK = 'ADD_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const MARK_AS_COMPLETED = 'MARK_AS_COMPLETED'
